version: '3.8'

services:
  todolist:
    build: ./backend
    image: todo-app:latest
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "3000:${SERVER_PORT}"
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/app/backend/node_modules

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata: {}
  node_modules: {}
